In [1]:
import json
with open("../artifacts/kaggle.json","r") as file:
    data =json.load(file)

In [2]:
data

{'username': 'ishanjayawardana98', 'key': '5facbc9e8591e88118a20500fb665c35'}

In [3]:
pip install kaggle

Requirement already satisfied: kaggle in c:\users\ishan\appdata\local\programs\python\python311\lib\site-packages (1.5.16)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: six>=1.10 in c:\users\ishan\appdata\local\programs\python\python311\lib\site-packages (from kaggle) (1.16.0)
Requirement already satisfied: certifi in c:\users\ishan\appdata\local\programs\python\python311\lib\site-packages (from kaggle) (2023.7.22)
Requirement already satisfied: python-dateutil in c:\users\ishan\appdata\local\programs\python\python311\lib\site-packages (from kaggle) (2.8.2)
Requirement already satisfied: requests in c:\users\ishan\appdata\local\programs\python\python311\lib\site-packages (from kaggle) (2.31.0)
Requirement already satisfied: tqdm in c:\users\ishan\appdata\local\programs\python\python311\lib\site-packages (from kaggle) (4.65.0)
Requirement already satisfied: python-slugify in c:\users\ishan\appdata\local\programs\python\python311\lib\site-packages (from kaggle) (8.0.1)
Requirement already satisfied: urllib3 in c:\users\ishan\appdata\local\programs\python\python311\lib\site-packages (from kaggle) (2.0.4)
Requirement already satisfied: bleach in c:\users\ishan\appdata\local\programs\python\python311\lib\site-packages (from kaggle) (6.0.0)
Requirement already satisfied: webencodings in c:\users\ishan\appdata\local\programs\python\python311\lib\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\ishan\appdata\local\programs\python\python311\lib\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\ishan\appdata\local\programs\python\python311\lib\site-packages (from requests->kaggle) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\ishan\appdata\local\programs\python\python311\lib\site-packages (from requests->kaggle) (3.4)
Requirement already satisfied: colorama in c:\users\ishan\appdata\local\programs\python\python311\lib\site-packages (from tqdm->kaggle) (0.4.6)

In [4]:
import os
os.environ["KAGGLE_USERNAME"]= data["username"]
os.environ["KAGGLE_KEY"]= data["key"]

In [5]:
from kaggle.api.kaggle_api_extended import KaggleApi
api = KaggleApi()
api.authenticate()

In [6]:
api.dataset_download_files("dhananjay28kumar/laptop-price", path ="../artifacts/")

In [7]:
import zipfile
with zipfile.ZipFile("../artifacts/laptop-price.zip","r") as zip_ref:
    zip_ref.extractall("../artifacts/")

In [8]:
import numpy as np
import pandas as pd

In [9]:
data = pd.read_csv("../artifacts/laptop_price.csv",encoding = "ISO-8859-1")

In [10]:
data.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60

In [11]:
data.shape

(1303, 13)

In [12]:
data.isnull()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,False,False,False,False,False,False,False,False,False,False,False,False,False
1299,False,False,False,False,False,False,False,False,False,False,False,False,False
1300,False,False,False,False,False,False,False,False,False,False,False,False,False
1301,False,False,False,False,False,False,False,False,False,False,False,False,False
1302,False,False,False,False,False,False,False,False,False,False,False,False,False

In [13]:
data.isnull().sum()

laptop_ID           0
Company             0
Product             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Memory              0
Gpu                 0
OpSys               0
Weight              0
Price_euros         0
dtype: int64

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   laptop_ID         1303 non-null   int64
 1   Company           1303 non-null   object
 2   Product           1303 non-null   object
 3   TypeName          1303 non-null   object
 4   Inches            1303 non-null   float64
 5   ScreenResolution  1303 non-null   object
 6   Cpu               1303 non-null   object
 7   Ram               1303 non-null   object
 8   Memory            1303 non-null   object
 9   Gpu               1303 non-null   object
 10  OpSys             1303 non-null   object
 11  Weight            1303 non-null   object
 12  Price_euros       1303 non-null   float64
dtypes: float64(2), int64(1), object(10)
memory usage: 132.5+ KB

In [15]:
data.head(1)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69

In [16]:
data["Ram"]= data["Ram"].str.replace("GB","").astype("int32")
data["Weight"]= data["Weight"].str.replace("kg","").astype("float32")

In [17]:
data.head(5)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,256GB SSD,Intel HD Graphics 620,No OS,1.86,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,512GB SSD,AMD Radeon Pro 455,macOS,1.83,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37,1803.60

In [18]:
data["Company"].value_counts()

Company
Dell         297
Lenovo       297
HP           274
Asus         158
Acer         103
MSI           54
Toshiba       48
Apple         21
Samsung        9
Razer          7
Mediacom       7
Microsoft      6
Xiaomi         4
Vero           4
Chuwi          3
Google         3
Fujitsu        3
LG             3
Huawei         2
Name: count, dtype: int64

In [19]:
def add_company(input):
    if input =="Samsung" or input =="Razer" or input =="Mediacom" or input =="Microsoft" or input =="Xiaomi" or input =="Vero" or input =="Chuwi" or input =="Google" or input =="Fujitsu" or input =="LG" or input == "Huawei":
        return "Other"
    else:
        return input

data["Company"] = data["Company"].apply(add_company)

In [20]:
data["Company"].value_counts()

Company
Dell       297
Lenovo     297
HP         274
Asus       158
Acer       103
MSI         54
Other       51
Toshiba     48
Apple       21
Name: count, dtype: int64

In [21]:
data["Product"].value_counts()

Product
XPS 13                                     30
Inspiron 3567                              29
250 G6                                     21
Legion Y520-15IKBN                         19
Vostro 3568                                19
                                           ..
15-bw007nv (A10-9620P/6GB/128GB/Radeon      1
SmartBook 130                               1
A541NA-GO342 (N3350/4GB/500GB/Linux)        1
17-X047na (i3-6006U/8GB/1TB/W10)            1
V330-15IKB (i5-8250U/4GB/500GB/FHD/W10)     1
Name: count, Length: 618, dtype: int64

In [22]:
len(data["Product"].value_counts())

618

In [23]:
data["TypeName"].value_counts()

TypeName
Notebook              727
Gaming                205
Ultrabook             196
2 in 1 Convertible    121
Workstation            29
Netbook                25
Name: count, dtype: int64

In [24]:
data["ScreenResolution"].value_counts()

ScreenResolution
Full HD 1920x1080                                507
1366x768                                         281
IPS Panel Full HD 1920x1080                      230
IPS Panel Full HD / Touchscreen 1920x1080         53
Full HD / Touchscreen 1920x1080                   47
1600x900                                          23
Touchscreen 1366x768                              16
Quad HD+ / Touchscreen 3200x1800                  15
IPS Panel 4K Ultra HD 3840x2160                   12
IPS Panel 4K Ultra HD / Touchscreen 3840x2160     11
4K Ultra HD / Touchscreen 3840x2160               10
4K Ultra HD 3840x2160                              7
Touchscreen 2560x1440                              7
IPS Panel 1366x768                                 7
IPS Panel Quad HD+ / Touchscreen 3200x1800         6
IPS Panel Retina Display 2560x1600                 6
IPS Panel Retina Display 2304x1440                 6
Touchscreen 2256x1504                              6
IPS Panel Touchscreen 2560x1440                    5
IPS Panel Retina Display 2880x1800                 4
IPS Panel Touchscreen 1920x1200                    4
1440x900                                           4
IPS Panel 2560x1440                                4
IPS Panel Quad HD+ 2560x1440                       3
Quad HD+ 3200x1800                                 3
1920x1080                                          3
Touchscreen 2400x1600                              3
2560x1440                                          3
IPS Panel Touchscreen 1366x768                     3
IPS Panel Touchscreen / 4K Ultra HD 3840x2160      2
IPS Panel Full HD 2160x1440                        2
IPS Panel Quad HD+ 3200x1800                       2
IPS Panel Retina Display 2736x1824                 1
IPS Panel Full HD 1920x1200                        1
IPS Panel Full HD 2560x1440                        1
IPS Panel Full HD 1366x768                         1
Touchscreen / Full HD 1920x1080                    1
Touchscreen / Quad HD+ 3200x1800                   1
Touchscreen / 4K Ultra HD 3840x2160                1
IPS Panel Touchscreen 2400x1600                    1
Name: count, dtype: int64

In [25]:
len(data["ScreenResolution"].value_counts())

40

In [26]:
data["Touchscreen"] = data["ScreenResolution"].apply(lambda x:1 if "Touchscreen" in x else 0)
data["IPS"] = data["ScreenResolution"].apply(lambda x:1 if "IPS" in x else 0)

In [27]:
data.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Touchscreen,IPS
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,0,1
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34,898.94,0,0
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,256GB SSD,Intel HD Graphics 620,No OS,1.86,575.00,0,0
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,512GB SSD,AMD Radeon Pro 455,macOS,1.83,2537.45,0,1
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37,1803.60,0,1

In [28]:
data["Cpu"].value_counts()

Cpu
Intel Core i5 7200U 2.5GHz       190
Intel Core i7 7700HQ 2.8GHz      146
Intel Core i7 7500U 2.7GHz       134
Intel Core i7 8550U 1.8GHz        73
Intel Core i5 8250U 1.6GHz        72
                                ...
Intel Core M M3-6Y30 0.9GHz        1
AMD A9-Series 9420 2.9GHz          1
Intel Core i3 6006U 2.2GHz         1
AMD A6-Series 7310 2GHz            1
Intel Xeon E3-1535M v6 3.1GHz      1
Name: count, Length: 118, dtype: int64

In [29]:
len(data["Cpu"].value_counts())

118

In [30]:
data["Cpu_name"] = data["Cpu"].apply(lambda x:" ".join(x.split()[0:3]))

In [31]:
data.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Touchscreen,IPS,Cpu_name
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,0,1,Intel Core i5
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34,898.94,0,0,Intel Core i5
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,256GB SSD,Intel HD Graphics 620,No OS,1.86,575.00,0,0,Intel Core i5
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,512GB SSD,AMD Radeon Pro 455,macOS,1.83,2537.45,0,1,Intel Core i7
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37,1803.60,0,1,Intel Core i5

In [32]:
data["Cpu_name"].value_counts()

Cpu_name
Intel Core i7               527
Intel Core i5               423
Intel Core i3               136
Intel Celeron Dual           80
Intel Pentium Quad           27
Intel Core M                 19
AMD A9-Series 9420           12
Intel Celeron Quad            8
AMD A6-Series 9220            8
AMD A12-Series 9720P          7
Intel Atom x5-Z8350           5
AMD A8-Series 7410            4
Intel Atom x5-Z8550           4
Intel Pentium Dual            3
AMD A9-Series 9410            3
AMD Ryzen 1700                3
AMD A9-Series A9-9420         2
AMD A10-Series 9620P          2
Intel Atom X5-Z8350           2
AMD E-Series E2-9000e         2
Intel Xeon E3-1535M           2
Intel Xeon E3-1505M           2
AMD E-Series 7110             2
AMD A10-Series 9600P          2
AMD A6-Series A6-9220         2
AMD A10-Series A10-9620P      2
AMD Ryzen 1600                1
Intel Atom x5-Z8300           1
AMD E-Series E2-6110          1
AMD FX 9830P                  1
AMD E-Series E2-9000          1
AMD A6-Series 7310            1
Intel Atom Z8350              1
AMD A12-Series 9700P          1
AMD A4-Series 7210            1
AMD FX 8800P                  1
AMD E-Series 9000e            1
Samsung Cortex A72&A53        1
AMD E-Series 9000             1
AMD E-Series 6110             1
Name: count, dtype: int64

In [33]:
def set_processor(name):
    if name == "Intel Core i3" or name == "Intel Core i5" or name == "Intel Core i7":
        return name
    elif name.split()[0] == "AMD":
        return "AMD"
    else:
        return "Other"

data["Cpu_name"] =data["Cpu_name"].apply(set_processor)

In [34]:
data["Cpu_name"].value_counts()

Cpu_name
Intel Core i7    527
Intel Core i5    423
Other            155
Intel Core i3    136
AMD               62
Name: count, dtype: int64

In [35]:
data["Gpu"].value_counts()

Gpu
Intel HD Graphics 620      281
Intel HD Graphics 520      185
Intel UHD Graphics 620      68
Nvidia GeForce GTX 1050     66
Nvidia GeForce GTX 1060     48
                          ...
AMD Radeon R5 520            1
AMD Radeon R7                1
Intel HD Graphics 540        1
AMD Radeon 540               1
ARM Mali T860 MP4            1
Name: count, Length: 110, dtype: int64

In [36]:
data["Gpu_name"]= data["Gpu"].apply(lambda x:" ".join(x.split()[0:1]) )

In [37]:
data["Gpu_name"].value_counts()

Gpu_name
Intel     722
Nvidia    400
AMD       180
ARM         1
Name: count, dtype: int64

In [38]:
data = data[data["Gpu_name"]!= "ARM"]

In [39]:
data.shape

(1302, 17)

In [40]:
data["Gpu_name"].value_counts()

Gpu_name
Intel     722
Nvidia    400
AMD       180
Name: count, dtype: int64

In [41]:
data["OpSys"].value_counts()

OpSys
Windows 10      1072
No OS             66
Linux             62
Windows 7         45
Chrome OS         26
macOS             13
Mac OS X           8
Windows 10 S       8
Android            2
Name: count, dtype: int64

In [42]:
def set_os(input):
    if input=="Windows 10" or input =="Windows 7" or input =="Windows 10 S":
        return "Windows"
    elif input =="macOS" or input =="Mac OS X":
        return "Mac"
    elif input == "Linux":
        return input
    else:
        return "Other"

data["OpSys"] = data["OpSys"].apply(set_os)

In [43]:
data.head(2)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Touchscreen,IPS,Cpu_name,Gpu_name
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,128GB SSD,Intel Iris Plus Graphics 640,Mac,1.37,1339.69,0,1,Intel Core i5,Intel
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,128GB Flash Storage,Intel HD Graphics 6000,Mac,1.34,898.94,0,0,Intel Core i5,Intel

In [44]:
data["OpSys"].value_counts()

OpSys
Windows    1125
Other        94
Linux        62
Mac          21
Name: count, dtype: int64

In [45]:
data = data.drop(["laptop_ID","Product","Inches","ScreenResolution","Cpu","Gpu"],axis =1)

In [46]:
data.head()

,Company,TypeName,Ram,Memory,OpSys,Weight,Price_euros,Touchscreen,IPS,Cpu_name,Gpu_name
0,Apple,Ultrabook,8,128GB SSD,Mac,1.37,1339.69,0,1,Intel Core i5,Intel
1,Apple,Ultrabook,8,128GB Flash Storage,Mac,1.34,898.94,0,0,Intel Core i5,Intel
2,HP,Notebook,8,256GB SSD,Other,1.86,575.00,0,0,Intel Core i5,Intel
3,Apple,Ultrabook,16,512GB SSD,Mac,1.83,2537.45,0,1,Intel Core i7,AMD
4,Apple,Ultrabook,8,256GB SSD,Mac,1.37,1803.60,0,1,Intel Core i5,Intel

In [47]:
data["Memory"].value_counts()

Memory
256GB SSD                        412
1TB HDD                          223
500GB HDD                        132
512GB SSD                        118
128GB SSD +  1TB HDD              94
128GB SSD                         76
256GB SSD +  1TB HDD              73
32GB Flash Storage                37
2TB HDD                           16
64GB Flash Storage                15
512GB SSD +  1TB HDD              14
1TB SSD                           14
256GB SSD +  2TB HDD              10
1.0TB Hybrid                       9
256GB Flash Storage                8
16GB Flash Storage                 7
32GB SSD                           6
180GB SSD                          5
128GB Flash Storage                4
512GB SSD +  2TB HDD               3
16GB SSD                           3
512GB Flash Storage                2
1TB SSD +  1TB HDD                 2
256GB SSD +  500GB HDD             2
128GB SSD +  2TB HDD               2
256GB SSD +  256GB SSD             2
512GB SSD +  256GB SSD             1
512GB SSD +  512GB SSD             1
64GB Flash Storage +  1TB HDD      1
1TB HDD +  1TB HDD                 1
32GB HDD                           1
64GB SSD                           1
128GB HDD                          1
240GB SSD                          1
8GB SSD                            1
508GB Hybrid                       1
1.0TB HDD                          1
512GB SSD +  1.0TB Hybrid          1
256GB SSD +  1.0TB Hybrid          1
Name: count, dtype: int64

In [48]:
len(data["Memory"].value_counts())

39

In [49]:
data["Memory_value"]= data["Memory"].apply(lambda x:" ".join(x.split()[0:2]))

In [50]:
data["Memory_value"].value_counts()

Memory_value
256GB SSD       500
1TB HDD         224
128GB SSD       172
512GB SSD       138
500GB HDD       132
32GB Flash       37
2TB HDD          16
1TB SSD          16
64GB Flash       16
1.0TB Hybrid      9
256GB Flash       8
16GB Flash        7
32GB SSD          6
180GB SSD         5
128GB Flash       4
16GB SSD          3
512GB Flash       2
64GB SSD          1
32GB HDD          1
128GB HDD         1
240GB SSD         1
8GB SSD           1
508GB Hybrid      1
1.0TB HDD         1
Name: count, dtype: int64

In [51]:
def set_memory_value(value):
    
    if value.split()[1] == "SSD":
        return "SSD"
    elif value.split()[1] == "HDD":
        return "HDD"
    else:
        return "Other"

data["Memory_value"] = data["Memory_value"].apply(set_memory_value)

In [52]:
data["Memory_value"].value_counts()

Memory_value
SSD      843
HDD      375
Other     84
Name: count, dtype: int64

In [53]:
data =data.drop(["Memory"],axis =1)

In [54]:
data = pd.get_dummies(data)

In [55]:
data.head(2)

,Ram,Weight,Price_euros,Touchscreen,IPS,Company_Acer,Company_Apple,Company_Asus,Company_Dell,Company_HP,...,Cpu_name_Intel Core i3,Cpu_name_Intel Core i5,Cpu_name_Intel Core i7,Cpu_name_Other,Gpu_name_AMD,Gpu_name_Intel,Gpu_name_Nvidia,Memory_value_HDD,Memory_value_Other,Memory_value_SSD
0,8,1.37,1339.69,0,1,False,True,False,False,False,...,False,True,False,False,False,True,False,False,False,True
1,8,1.34,898.94,0,0,False,True,False,False,False,...,False,True,False,False,False,True,False,False,True,False

In [56]:
data_new =data.drop(["Ram","Weight","Price_euros"],axis =1).astype(int)
data_new

,Touchscreen,IPS,Company_Acer,Company_Apple,Company_Asus,Company_Dell,Company_HP,Company_Lenovo,Company_MSI,Company_Other,...,Cpu_name_Intel Core i3,Cpu_name_Intel Core i5,Cpu_name_Intel Core i7,Cpu_name_Other,Gpu_name_AMD,Gpu_name_Intel,Gpu_name_Nvidia,Memory_value_HDD,Memory_value_Other,Memory_value_SSD
0,0,1,0,1,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,1
1,0,0,0,1,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,1,0
2,0,0,0,0,0,0,1,0,0,0,...,0,1,0,0,0,1,0,0,0,1
3,0,1,0,1,0,0,0,0,0,0,...,0,0,1,0,1,0,0,0,0,1
4,0,1,0,1,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1,1,0,0,0,0,0,1,0,0,...,0,0,1,0,0,1,0,0,0,1
1299,1,1,0,0,0,0,0,1,0,0,...,0,0,1,0,0,1,0,0,0,1
1300,0,0,0,0,0,0,0,1,0,0,...,0,0,0,1,0,1,0,0,1,0
1301,0,0,0,0,0,0,1,0,0,0,...,0,0,1,0,1,0,0,1,0,0
1302,0,0,0,0,1,0,0,0,0,0,...,0,0,0,1,0,1,0,1,0,0

In [57]:
data_new["Ram"] = data["Ram"]
data_new["Weight"] = data["Weight"]
data_new["Price_euros"] = data["Price_euros"]
data_new

,Touchscreen,IPS,Company_Acer,Company_Apple,Company_Asus,Company_Dell,Company_HP,Company_Lenovo,Company_MSI,Company_Other,...,Cpu_name_Other,Gpu_name_AMD,Gpu_name_Intel,Gpu_name_Nvidia,Memory_value_HDD,Memory_value_Other,Memory_value_SSD,Ram,Weight,Price_euros
0,0,1,0,1,0,0,0,0,0,0,...,0,0,1,0,0,0,1,8,1.37,1339.69
1,0,0,0,1,0,0,0,0,0,0,...,0,0,1,0,0,1,0,8,1.34,898.94
2,0,0,0,0,0,0,1,0,0,0,...,0,0,1,0,0,0,1,8,1.86,575.00
3,0,1,0,1,0,0,0,0,0,0,...,0,1,0,0,0,0,1,16,1.83,2537.45
4,0,1,0,1,0,0,0,0,0,0,...,0,0,1,0,0,0,1,8,1.37,1803.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1,1,0,0,0,0,0,1,0,0,...,0,0,1,0,0,0,1,4,1.80,638.00
1299,1,1,0,0,0,0,0,1,0,0,...,0,0,1,0,0,0,1,16,1.30,1499.00
1300,0,0,0,0,0,0,0,1,0,0,...,1,0,1,0,0,1,0,2,1.50,229.00
1301,0,0,0,0,0,0,1,0,0,0,...,0,1,0,0,1,0,0,6,2.19,764.00
1302,0,0,0,0,1,0,0,0,0,0,...,1,0,1,0,1,0,0,4,2.20,369.00

In [58]:
x =data_new.drop(["Price_euros"],axis =1)
y =data_new["Price_euros"]

In [59]:
!pip install sklearn

Requirement already satisfied: sklearn in c:\users\ishan\appdata\local\programs\python\python311\lib\site-packages (0.0.post7)

In [60]:
pip install -U scikit-learn

Requirement already satisfied: scikit-learn in c:\users\ishan\appdata\local\programs\python\python311\lib\site-packages (1.3.0)
Requirement already satisfied: numpy>=1.17.3 in c:\users\ishan\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.25.2)
Requirement already satisfied: scipy>=1.5.0 in c:\users\ishan\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.11.1)
Requirement already satisfied: joblib>=1.1.1 in c:\users\ishan\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.3.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\ishan\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (3.2.0)
Note: you may need to restart the kernel to use updated packages.

In [61]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.25)

In [62]:
x_train.shape

(976, 34)

In [63]:
def model_acc(model):
    model.fit(x_train,y_train)
    acc = model.score(x_test,y_test)
    print(str(model) + " -> " + str(acc))

In [64]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
model_acc(lr)

LinearRegression() -> 0.708444619726238

In [65]:
from sklearn.linear_model import Lasso
lasso = Lasso()
model_acc(lasso)

Lasso() -> 0.7064096003748527

In [66]:
from sklearn.tree import DecisionTreeRegressor
dt = DecisionTreeRegressor()
model_acc(dt)

DecisionTreeRegressor() -> 0.7160718351016728

In [67]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor()
model_acc(rf)

RandomForestRegressor() -> 0.7882069984797899

In [70]:
from sklearn.model_selection import GridSearchCV
parameters = {"n_estimators": [10,50,100],
             "criterion": ["squared_error", "absolute_error", "poisson"]}
grid_object =GridSearchCV(estimator = rf,param_grid =parameters)
grid_fit =grid_object.fit(x_train,y_train)
best_model = grid_fit.best_estimator_
best_model

RandomForestRegressor(n_estimators=50)

In [71]:
best_model.score(x_test,y_test)

0.7936107818125782

In [72]:
import pickle
with open("Laptop_price_predictor.pickle","wb") as file:
    pickle.dump(best_model,file)

In [73]:
x_train.columns

Index(['Touchscreen', 'IPS', 'Company_Acer', 'Company_Apple', 'Company_Asus',
       'Company_Dell', 'Company_HP', 'Company_Lenovo', 'Company_MSI',
       'Company_Other', 'Company_Toshiba', 'TypeName_2 in 1 Convertible',
       'TypeName_Gaming', 'TypeName_Netbook', 'TypeName_Notebook',
       'TypeName_Ultrabook', 'TypeName_Workstation', 'OpSys_Linux',
       'OpSys_Mac', 'OpSys_Other', 'OpSys_Windows', 'Cpu_name_AMD',
       'Cpu_name_Intel Core i3', 'Cpu_name_Intel Core i5',
       'Cpu_name_Intel Core i7', 'Cpu_name_Other', 'Gpu_name_AMD',
       'Gpu_name_Intel', 'Gpu_name_Nvidia', 'Memory_value_HDD',
       'Memory_value_Other', 'Memory_value_SSD', 'Ram', 'Weight'],
      dtype='object')